# Generated by Django 2.2 on 2020-11-29 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin (superuser or admin)'), (2, 'Member')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Fee', 'Fee'), ('Loan', 'Loan')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone_home', models.CharField(blank=True, max_length=200, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=200, null=True)),
                ('nid', models.CharField(blank=True, max_length=200, null=True)),
                ('representative_name', models.CharField(blank=True, max_length=200, null=True)),
                ('representative_father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('representative_mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('representative_address', models.CharField(blank=True, max_length=200, null=True)),
                ('member_subscription_receipt_no', models.CharField(blank=True, max_length=200, null=True)),
                ('member_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField(default=0.0)),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Deposit', 'Deposit'), ('Expense', 'Expense')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.FloatField()),
                ('amount_in_word', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], max_length=200)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Issue')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Member')),
                ('transactiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.TransactionType')),
            ],
        ),
    ]
